### ISSUE TITLE
Displaying surfaces in IJulia

### ISSUE THREAD

**Issue by sswatson** [JuliaGraphics/Cairo.jl#143]
The default presentation for a Cairo surface in an IJulia notebook used to be a png image, whereas now I just get a string which looks like 

`Cairo.CairoSurface{UInt32}(Ptr{Void} @0x00007fd44bf88f00,256.0,256.0,#undef)`

Is this an intended change? If so, how can I get my images to render inside my IJulia browser?

**Comment by timholy** [comment]
Maybe do `Pkg.update`? It's possibly due to the `writemime` change (7477b01bc460ed9df369d4b16615e1891594bc5d, part of #139), you might need a new Compat. If that doesn't fix it, would you please provide `versioninfo()` and the results of `Pkg.status()`? If you're up for testing, it could also be 66c0353335425c878ecd6a2e5f374ef219bbecd5 or #142, and trying different versions of the package (if you know enough about git to do so) might help reveal the source of the problem.

This package is definitely lacking in tests, so any changes are indeed at risk for unintentionally breaking stuff. #144, while it probably doesn't fix anything, is an attempt to test this functionality (and it seems to be passing). If you notice other breakages, please do mention it. Or even better, add whatever fixes & tests you can yourself!

**Comment by timholy** [comment]
@sswatson, GitHub closed this automatically by merging #144, but if this isssue is still broken for you, we'll reopen.

**Comment by sswatson** [comment]
Thanks for the help. The issue is definitely related to the `writemime` change, because if I run 

```julia
import Base.writemime
writemime(io::IO, ::MIME"image/png", surface::CairoSurface) = write_to_png(surface, io)
```

then my Cairo surfaces display properly. I haven't solved the problem (without having to insert the above lines, I mean), but I have some further thoughts: 

1. Should there perhaps be a `@compat import Base.show` line in `Cairo.jl`? This seems to be how it works in `Compat`'s tests. Also, this `macroexpand`s to `import Base.writemime`, which seems like the right thing (I'm using Julia 0.4.6). 

2. I `macroexpanded` the `@compat function Base.show(...)` line currently in `Cairo.jl`, and it isn't defining Base.writemime, which it seems to me like what it should do. I don't have enough knowledge about this issue to be confident, but IJulia is looking to Base.writemime for how to render the surfaces, right? 

```julia 
julia> versioninfo()
Julia Version 0.4.6
Commit 2e358ce (2016-06-19 17:16 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

Relevant package versions: 

 - Cairo                         0.2.32
 - Compat                        0.8.1

**Comment by timholy** [comment]
Great detective work! Indeed, on Julia 0.4 it's essential to define `writemime`, and this definitely isn't doing that. 
It seems to be a limitation on how Compat expands these expressions. I wonder whether #145 fixes it: is it too much to ask you to test it? These days I'm running 0.5.

**Comment by sswatson** [comment]
Cool, that PR fixes the problem. Thanks!
