### ISSUE TITLE
next release

### ISSUE THREAD

**Issue by lobingera** [JuliaGraphics/Cairo.jl#192]
- [x] track down if IOStream support for ios/apple is still needed (looks like write to stream via libuv is available in ios also)
- [ ] clarify 32bit windows failure -> https://github.com/JuliaPackaging/WinRPM.jl/issues/107
- [ ] clarify script to file failures on Win
- [x] #191 
- [x] set correctly travis binaries, move testing to 0.4/0.5/0.6 (latest-0.7 only on a next master)

**Comment by lobingera** [comment]
for those waiting for this: the 32bit failure keeps me busy.

**Comment by musm** [comment]
perhaps we could get a tag soon and work on the win32 failures later?

**Comment by lobingera** [comment]
I'd agreed in principle, but that means to turn off 32 Bit testing

**Comment by ararslan** [comment]
> but that means to turn off 32 Bit testing

Not necessarily. The overall CI status will be red because of 32-bit failures, but you can still check the logs to ensure that the other architectures are passing.

**Comment by lobingera** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/10607

**Comment by tkelman** [comment]
I'd recommend dropping 0.4 support sooner rather than later unless you absolutely need it, it's been quite a few months since the last tag and this package has a few downstream dependents. Since many of those downstream packages are no longer actively being maintained for old versions of Julia, it would be unfortunate to have a new release of Cairo cause any problems that never get fixed on those versions of Julia.

**Comment by lobingera** [comment]
@tkelman (see above), i'm planning to go with master to 0.5/0.6/0.7 soon.
What do you mean with "package has a few downstream dependents"?

**Comment by tkelman** [comment]
I mean there are several other packages that depend on Cairo.jl

**Comment by lobingera** [comment]
I know, but was the general setup: (julia) current release + two before?

**Comment by tkelman** [comment]
That depends on the package. Hardly anyone goes to the trouble of supporting 3 different releases at the same time. 1 or 2 is more common.

**Comment by lobingera** [comment]
I see. btw: what is actually this: http://juliarun-ci.s3.amazonaws.com/5025641759d0800a8cfc746285522a4201f3619f/Cairo_reverse_dependency_tests.html ?

**Comment by tkelman** [comment]
It's a new thing we're doing where we run some reverse-dependency package tests on new tags. Since it doesn't have the cairo libraries installed in the VM it runs in and BinDeps' apt-get usage is broken, it's not so useful right now. When we have a replacement for BinDeps that handles libraries better it'll be more useful to test in minimal environments like that.
