### ISSUE TITLE
copy!(::Cairo.CairoContext, ::Matrix) removed?

### ISSUE THREAD

**Issue by tknopp** [JuliaGraphics/Cairo.jl#198]
Hi, I have code that uses 

copy!(::Cairo.CairoContext, ::Matrix). Has this function been removed? I now get the following error:

```
ERROR: MethodError: no method matching copy!(::Cairo.CairoContext, ::Array{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2})
Closest candidates are:
```

@lobingera

**Comment by tknopp** [comment]
Ah, forget it. This function is in GtkUtilities.jl which I dropped for some reason. sorry for the noise.

**Comment by tkelman** [comment]
That's not the most obvious place for that method to be. It should perhaps be moved here if possible.

**Comment by tknopp** [comment]
yep, I thought the same.

**Comment by timholy** [comment]
Certainly I'd have no objections to adding (or have someone grab and contribute) those methods here.

But it's the age-old question: should wrapper packages remain faithful to the original API or provide a nice Julian interface? "faithful" has won out here in the past, but of course times change so I shouldn't assume. Gtk vs GtkReactive is an even more extreme version: Gtk is pretty faithful to the C library, and GtkReactive abstracts it to the point where you can barely tell you're using Gtk.

**Comment by lobingera** [comment]
we don't cover the full cairo C-API, what should the above mentioned function do?

**Comment by lobingera** [comment]
@timholy Actually Gtk/GtkReactive is the best situation: Clear (C-)API with Gtk, higher layer abstraction with GtkReactive. In case of need, Cairo could be split to Cairo and CairoUtil?

**Comment by tknopp** [comment]
Gtk/GtkReactive is IMHO a different thing. Here, its just a convenient way of drawing an array to the canvas. Actually, Gtk.jl is actually not that thin since various iterator protocols are already modeled using Julia syntax. For me the `copy!` plays in the same league.

**Comment by lobingera** [comment]
The steps to paint a Matrix of colored pixel into an available context are short, you could follow the example in
https://github.com/JuliaGraphics/Cairo.jl/blob/master/samples/sample_alpha_paint.jl#L10-L27
and replace the filter, extend and scaling (input to CairoMatrix)

**Comment by timholy** [comment]
I agree it's not difficult, but for someone who doesn't already have Cairo's API memorized it still means a trip to the manual, and if you've not already spent a certain amount of time reading it takes a while to dig out the nugget you're looking for. Contrast that with `copy!(dest, src)`, which I bet many Julians would think of on their own. Likewise, if you want to paint the whole canvas with a solid color, `fill!(dest, rgb)` immediately comes to mind.

For reference, [here](https://github.com/JuliaGizmos/GtkReactive.jl/blob/ae6d8d6b05a3960d937f6b433bf5250f4fd72039/src/graphics_interaction.jl#L295-L325) are the definitions of those methods in GtkReactive. (The utility functions at the end are simply for ensuring that we do as little copying of data as possible, while also handling many different types of surfaces/color data.) I'd say it's @lobingera's call, since you're the one doing the maintenance work here; if you're excited about having them, I'm happy to make a PR, otherwise they should live somewhere else. GtkReactive has been my answer to where, but I'm happy to consider alternatives.

**Comment by tknopp** [comment]
@timholy that the same lines are also in `GtkUtilities` https://github.com/timholy/GtkUtilities.jl/blob/master/src/GtkUtilities.jl#L47

tells me that there is some room for improvement.

Regarding if there should be a CairoUtils.jl package I vote for being pragmatic. If its a small number of functions than just let this live in Cairo.jl. If its gets too much one can always split of CairoUtils.jl later.

**Comment by tkelman** [comment]
My answer to the "where should things live" question is generally based on where the types and functions are defined. It's slightly ambiguous when the type signature spans multiple packages (in this case I think we'd need to make the FixedPointNumbers dependency direct instead of indirect), but when it's a Base function and a single package's types, adding a separate utilities package because the C API and the Julia API are a bit different doesn't seem like a satisfying solution to me. Gtk itself isn't necessarily going to depend on Reactive so that level of separation makes sense, but the miscellaneous other methods going along for the ride always looked a little off to me.

The different API levels could be put in different sub-modules of the same package if that helps with organization, but dependencies are tracked at the package level rather than the method level. It gets confusing to have to remember where individual methods are defined if it's done in a different package than the types involved.

**Comment by timholy** [comment]
@tknopp, please also notice the statement in "alternatives": https://github.com/timholy/GtkUtilities.jl#alternatives. From my standpoint the fact that they are duplicated isn't a problem because GtkUtilities is on its way out. I'm not in a hurry to ditch it though, as long as it isn't any real work to maintain.

Agreed @tkelman, and in this case I personally like the idea of having the `copy!`/`fill!` methods here. But really I think that's for @lobingera to decide; those who are willing to do the work get to win :smile:.

**Comment by lobingera** [comment]
(sorry for the late reply, i'm traveling right now)

There are already some 'julian' adaptations, like allowing input to set_source, the way some surfaces are constructed and the context type as container for cairo-context and the pango-context (which gave me some headache some time ago - as Gtk returns a pure cairo-context from some widgets).

The first way i used libcairo was via pycairo https://pycairo.readthedocs.io/en/latest/ (in a previous incarnation) and this is already adapts the pure C-API to classes and methods. And if you're interested there is whole chapter about library language adaptation in the cairo doc
https://cairographics.org/manual/language-bindings.html

I think, it's tempting to look at the simplicity to use copy! to put a bitmap into a surface or fill! to fill the 'whole' surface, keep in mind, that the underlying operations (see my comment about reusing the logic in sample_alpha) are quite complex.

If you think that a simple copy! and fill! is needed -> PR
