### ISSUE TITLE
Use BinaryBuilder/BinaryProvider

### ISSUE THREAD

**Issue by davidanthoff** [JuliaGraphics/Cairo.jl#214]
Has anyone started thinking about using those for the binary dependencies? That might add some welcome stability to the package?

**Comment by lobingera** [comment]
Maybe it's just me, but https://github.com/JuliaPackaging/BinaryProvider.jl/ itself announces it with [WIP] and build failing in most cases. How do you come to the idea that this introduces more stability here?
(read as: i would be pleased to replace BinDeps / Homebrew / WinRPM, but i want to see this working first...)

**Comment by davidanthoff** [comment]
Oh yeah, I'm not saying that it is ready. But it is looking quite promising, and I was just wondering whether folks have started thinking about it in relation to this package here. I've successfully used it for a much, much simpler project, and so far so good. Main benefit seems to be that there is no reliance on things like the opensuse servers etc. anymore.

My guess is that Cairo.jl would be one of the more challenging packages for this new BinDeps2 combo, so it might also be a really good stress test for the design of the new binary delivery stuff?

**Comment by lobingera** [comment]
I'll see your PR (as WIP).

**Comment by davidanthoff** [comment]
I think the folks that are building BinaryProvider/BinaryBuilder might actually take a crack at it :) You won't see a PR from me, these build things drive me absolutely crazy and I don't understand enough of that kind of thing to stand even a slight chance of being successful with that kind of project.

**Comment by SimonDanisch** [comment]
Gave it a try here:
https://github.com/JuliaGraphics/CairoBuilder/issues/1
Of course it didn't work on first try ;)

**Comment by SimonDanisch** [comment]
![grafik](https://user-images.githubusercontent.com/1010467/42682861-0048f704-868c-11e8-8389-4ed7209e90b6.png)

First build of Cairo for most platforms went through :) Right now I'm building the remaining (more obscure) platforms and I see no reason why they should fail ;)

But we might be in a problematic situation now.
 
This is a minimal build of Cairo, without any of the more advanced backends like GTK or xserver.
I'm not sure if one can link those in dynamically - but as it stands I'm perfectly happy with this minimal Cairo binary for my purposes. On the other hand, GTK will take quite a while untill we can offer it via BinaryProvider and to be honest I gave up on GTK - every time I try it out it gives me a new segfault, heisenbug or obscure behaviour and it's such a big library that I feel a bit overwhelmed at the thought of fixing it.
So, since I'm happy with this binary and others may not, I'm not really sure how we can cater different binaries to different audiences of Cairo! Maybe we'll even need a fork? 
I hope this ends up as a non issue, since GTK possibly just ships Cairo, so people who use it with GTK could just rely on that?!

In any case, I'll prepare a PR to Cairo and see if the test pass with the current binaries to get things started!

**Comment by tknopp** [comment]
Gtk.jl has to be compatible with Cairo.jl. This won't work if they use different Cairo binaries. I would strongly prefer not doing 0.6 -> 0.7 transition simultaneously with the transition to BinaryBuilder. This BinaryBuilder thing looks like a massive effort to get fully done and this should happen in a coordinated fashion so that the user of the packages gets a smooth transition.

**Comment by SimonDanisch** [comment]
let's move the discussion to #229

**Comment by giordano** [comment]
An update of what I'm doing.  First of all, I moved development of the builders to https://github.com/JuliaPackaging/Yggdrasil, as this is the place where all builders should move at some point for convenience.

* I managed to build Cairo with a native backend for macOS and Windows: https://github.com/JuliaPackaging/Yggdrasil/pull/39
* For macOS and Windows, I managed to build Pango with support for Cairo: https://github.com/JuliaPackaging/Yggdrasil/pull/41

I'd like to stress that I didn't actually test these builds, so I'm no sure they're working at all, but at least I compiled successfully :slightly_smiling_face:.

What remains to do:

* add a native Cairo backend for Linux and FreeBSD.  This requires building libX11 (at least for Linux, I hope it'll be good also for FreeBSD), I have no idea how easy it'll be.

**Comment by SimonDanisch** [comment]
Would a Xorbuilder help with this?
https://github.com/JuliaGraphics/XorgBuilder/releases

**Comment by giordano** [comment]
> Just in terms of high level strategy: is the plan then to also add a Gtk builder to Yggdrasil? Because my understanding had been that we can only move Cairo.jl here over to a new binary if we also have the Gtk.jl binary story sorted out, right?

I don't have a plan, I just build random packages :joy: Cairo doesn't need to build whole Gtk to build, you can see here Cairo's dependencies:
https://github.com/JuliaPackaging/Yggdrasil/blob/eefd9238db11fe58849422d5ee3e5adce3eb3db9/C/Cairo/build_tarballs.jl#L53-L59.

> Would a Xorbuilder help with this?

Wow, I didn't know there was one!  I don't think Cairo needs whole Xorg, only libX11 (and its dependencies, like xproto and maybe something else) should be required, but it's encouraging to see that BinaryBuilder worked at least on one platform for whole Xorg!

**Comment by giordano** [comment]
> I think the concern of the folks maintaining Cairo.jl is that if they switch over to binaries for cairo that don't work with Gtk.jl, then Gtk.jl would be broken, which wouldn't be acceptable.

Do the two packages need to talk to each other?  I'm asking because I really don't know anything about this.

Anyway, I think that if we succeed in building Cairo, someone will undertake the Gtk adventure, too.

**Comment by giordano** [comment]
Right, Gtk.jl depends on Cairo.jl, but if they only talk to each other through julia and there is no direct communication between the underlying C libraries I don't expect that there could be problems.

**Comment by giordano** [comment]
By the way, I got an almost working libX11 build (it's not building only on Windows x86_64, but this is not worrying for as far as Cairo is concerned): https://github.com/JuliaPackaging/Yggdrasil/pull/42.

Now we only need to put all the builders together. This means building Cairo for Linux and FreeBSD with x11 support and use it to build Pango, then test that all these libraries we've built can be finally used in Cairo.jl

**Comment by tknopp** [comment]
Gtk uses Cairo directly. In fact, the entire rendering is done through Cairo.

The dependencies of Gtk are listed here:

https://developer.gnome.org/gtk3/stable/gtk-building.html

I think it makes absolutely sense to make this step by step. As long as Cairo does not make a release, everything is fine. Even if you do, we could pin the version of Cairo in Gtk. Just to highlight, why it is important to get both working: Winston.jl requires Cairo and Gtk and it will break if only Cairo is working.
