### ISSUE TITLE
libcairo not found, Julia master, apple silicon

### ISSUE THREAD

**Issue by domschl** [JuliaGraphics/Cairo.jl#344]
Even so according to https://github.com/JuliaPackaging/Yggdrasil/pull/3062 a Cairo_jll version for :aarch64 should be available, installation fails on Mac M1:
```
julia> using Cairo
[ Info: Precompiling Cairo [159f3aea-2a34-519c-b102-8c37f9878175]
ERROR: LoadError: UndefVarError: libcairo not defined
```

**Comment by giordano** [comment]
What version of Cairo_jll do you have in your environment? It's likely you have 1.16.0 instead of 1.16.1. Tests of Cairo pass for me. You can see the version with `]st -m`.

Also, [as I already told you](https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/1072), for issues with missing libraries on this platform refer to https://github.com/JuliaPackaging/Yggdrasil/issues/2763. Don't open issues in other repositories, there is nothing the other developers will be able to do anyways and you just spread around your requests where it's hard to track them.

**Comment by domschl** [comment]
I am sorry for creating mess.

Yes I had 1.16.0 and that's what gets installed after removing Cairo (and Cairo_jll). Version 1.16.1 is not offered, neither as update nor at new installs.
`add Cairo_jll@1.16.1` indeed worked.

Anyway, thanks again for your help!
